### ISSUE TITLE
Using HTTP(S) Proxys?

### ISSUE THREAD

**Issue by JohannesBauer97** [hfreire/pollmommy#176]
Hi, 

Is there a way to set a http proxy?
Would be perfect for the `_options` field.

Thanks

**Comment by hfreire** [comment]
Hi @Waterfront97!

Yes you can, through the nightmare proxy option.

Take a look at how I am doing it here: 
https://github.com/hfreire/make-porto-win-european-best-destination-2017/blob/2b6effb7902f24a1af7e2ea86f64727166ea058a/src/voting-poll.js#L36

If you have time, maybe we could help other people with the same question by updating the example in this repo with the proxy option. Thank you!
