### ISSUE TITLE
Node 8 causes postinstall error

### ISSUE THREAD

**Issue by spookyuser** [hfreire/pollmommy#57]
Love the idea of this npm module :P but whenever I try and install globally on Ubuntu I run into [this](https://github.com/electron/electron/issues/9323) error.

If you even try running it on [runkit](https://npm.runkit.com/pollmommy) the same thing happens :/

Don't know how to fix it.

**Comment by hfreire** [comment]
Hi!

I've just tried a global installation in a `OSX/Sierra` and `Linux/Debian` of `pollmommy@1.0.6` with success - both running `node@6.11.1` and `npm@3.10.10`.

Let's do the following:

1. Share your npm installation debug log to verify that it is the same issue you are referring to?
2. Share your node and npm versions by running `node --version && npm --version`.
3. I've released `pollmommy@1.0.7` which updates several dependencies - install the last version and give it a try.

**Comment by spookyuser** [comment]
So I tried with Node 6 and it's working now. Maybe it's an issue with Node 8. I can reinstall it later and grab the log file if you'd like?

**Comment by hfreire** [comment]
Yes, feel free to attach a debug log here so I can address the issue.

**Comment by spookyuser** [comment]
Sorry it took me so long :P
[debug.txt](https://github.com/hfreire/pollmommy/files/1179625/debug.txt)

**Comment by hfreire** [comment]
I've successfully tested it with Node `v8.9.0`. The issue might no longer be present. Closing the issue for now.
